### ISSUE TITLE
Items filtrered correctly but not getting deleted

### ISSUE THREAD

**Issue by exelinguy** [terrelsa13/media_cleaner#128]
Hello! I hope you are having a great weekend. Firstly, thank you so much for creating this wonderful little cool program.

I have configured the program currectly and ensured that correct os permissions are given to emby user. I have marked REMOVE_FILES as true. The script is filtering out played items as expected (simply marking episodes for deletion as soon as they have been played once), however none are getting deleted. It might be something silly, but I am not able to figure it out! I would be grateful if you could please tell me how I can get the script to execute deletion part as well.

From the logs I can see that for each of the filtered episodes, the IsMeetingAction and IsMeetingPlayedFilter flags are true. However, in the the PROCESSING BLACKLISTED EPISODES section, the flags are simply set to None / Null...

I have attached the level 4 debug log: [mumc_DEBUG.log.txt.log](https://github.com/user-attachments/files/16829506/mumc_DEBUG.log.txt.log)

Thanks!

**Comment by terrelsa13** [comment]
Hi. All is well. Thank you very much. Hope you are having a great weekend too.

Ok, I took a look at your logs and only one thing stood out. It should not make a difference, but worth trying. Change the `matching: byPath` to `matching: byId`. This should not matter, but worth a try. While I look deeper into why media_items are not deleting for you.

```yaml
admin_settings:
  behavior:
    matching: byId
```

While we figure this out, please change `REMOVE_FILES: true` to `REMOVE_FILES: false` to ensure we do not accidentally delete more media_items than expected. With `REMOVE_FILES: false` we should still be able to see which media_items are supposed to be deleted.

**Comment by exelinguy** [comment]
Thank you so much for your kind and fast response! 

I tried changing the `matching: byPath` to `matching: byId` , but it hasn't changed the behaviour. I've changed the `REMOVE_FILES` flag as per your guidance for future testing as needed.

**Comment by exelinguy** [comment]
Oops. Closed the issue by mistake, sorry.

**Comment by terrelsa13** [comment]
> Oops. Closed the issue by mistake, sorry.

Np.

### Long Answer:
A while back I started to use Emby's subfolder library Ids to allow more granular controls. However I learned shortly after the parent subfolder library Ids for two items sharing a parent are not the same. The subfolder library Id changes were edited to force regular library Ids for emby instead of subfolder library Ids. During the transition I missed changing two variables from `subfolder_id` to `lib_id`.

### Short Answer:
Looks like this was 100% my fault. Apologies for causing you any confusion. And thank you for finding this.

##

Try the latest [release v5.8.35](https://github.com/terrelsa13/MUMC/releases).

Run it a few times with `REMOVE_FILES: false`. After you are comfortable it is showing the expected media_items to be deleted. Go ahead and change to `REMOVE_FILES: true`.

**Comment by exelinguy** [comment]
Wow, you are such a rockstar for figuring out something like this. I don't think it's your "fault" in any way. I mean it's a program to delete watched and old files from a media management and player software on media servers, that too with so many moving pieces! 😁

I find this stuff really fascinating, even though I don't fully understand the long answer and my programming skills are, at best, very elementary.

I'm currently traveling and don't have external access to my server (yet). Will get back tomorrow and try out the new version and update you.

Thank you once again for this wonderful gift! ❤️

**Comment by exelinguy** [comment]
I was able to check and it is working absolutely beautifully now. Thank you!
