### ISSUE TITLE
Plain, new config creates an error.

### ISSUE THREAD

**Issue by upD8R** [terrelsa13/media_cleaner#129]
### Have You Read The Wiki?:

No

### Describe What You Are Trying To Accomplish:

I had it up and running but then decided to upgrade and now I'm lost. Initial config created, just a very basic one. Yet it doesn't work.

### Describe What Is Happening:

Running the script creates an error.

### Any Additional Information You Think Will Be Useful:

ConfigValueError: admin_settings > users > user_id: 19b4d0786b044a7982dbc0e33ce963c1 > blacklist > library_id: 62c730a74d224ac5975e74be459f9ce7 > path: E:\Movies - Medien is not an expected string value
ConfigValueError: admin_settings > users > user_id: 19b4d0786b044a7982dbc0e33ce963c1 > blacklist > library_id: 828e9b570118467e95f49296719e9569 > path: E:\Shows - Medien is not an expected string value

**Comment by upD8R** [comment]
Okay, got it. Had to replace the path in the config with "null". But should a path create such an error?

**Comment by terrelsa13** [comment]
> Okay, got it. Had to replace the path in the config with "null". But should a path create such an error?

You are correct. It should not generate an error.

I always forget windows uses backslash `\` instead of forward-slash `/` to separate directories.
Issue has been fixed in both **MUMC-Latest** and **MUMC_beta**.
Updates for both have been pushed to their respective trunks and can also be found [here](https://github.com/terrelsa13/MUMC/releases).

**Comment by upD8R** [comment]
Thanks for the support!
