### ISSUE TITLE
Feature Request: Monitor for delete based on tag(s)

### ISSUE THREAD

**Issue by SenorSmartyPants** [terrelsa13/media_cleaner#14]
Only monitor for delete if a tag is set on object. Sort of like favoriting, but in reverse. Most things in my (TV) library I want to keep but there are some (daily and weekly shows) that I definitely want to get rid of. I could tag these to be monitored.

If the tag option is enabled for a library, then only tagged items would be checked for deletion.

**Comment by terrelsa13** [comment]
This could be a good idea. But I have a couple questions.

1. I see how to add tags in the Emby/JF GUIs. But how are you adding tags to media items (i.e. GUI, script, etc...)?

2. Will you help me see how over a long period of time it is more efficient to select what to delete vs what not to delete?

**I will try to explain how I am seeing it in my head:** All storage has a limit. If lots of media is being permanently kept sooner or later the limit is reached. When this happens I see two options; adding storage or untagging the media that is tagged to not be deleted. Upfront it may lower the number of media items that need to be touched. But it pushes the cleanup work to the backend when disk space is low. It seems at that point it would become a more critical nuisance. The script has the ability to keep all children if series or season are set to favorite. Yes, that means the media has to be favorited upfront. But it also forces that upfront thought to go into what will be taking up disk space vs what will not take up disk space. It seems unintuitive. Am I missing something?

**Comment by SenorSmartyPants** [comment]
1. GUI
2. I don't know if something will become a favorite when I start watching. I could make the delete days several months to decide I suppose. 

But the other thing is eventually almost everything will be set as a favorite because everything else will be deleted. And then favorite becomes an almost meaningless distinction. Yes, I have a bit of a data hoarder mentality.

**Comment by terrelsa13** [comment]
Ok. I follow you now. I like the idea of tags, I will start to implement this when I have free time (you know, between the job that pays and other life stuff).

**My Vision On How This Gets Implemented Into The Script:**
- I am on the fence if this should be part of the first run configuration setup walk-thru process or if it should be setup manually in the configuration file only. Less is more. If it does become part of the walk-thru process; it will ask for a tag string and how to treat the tag (i.e. tag is for deleting media items or tag is for keeping media items).
- That string will be the string it expects to see associated to a media item during normal runs (it will likely start out as just series, season, episode; but may grow to movies, albums, music, etc...).

Any feedback/suggestions you have on how I am seeing this implemented?

**Comment by SenorSmartyPants** [comment]
Implementation seems fine. I'm assuming you've got a working test API call with tag filtering working. If not, I'm happy to assist/test.

As far as my use goes, I mainly plan on tagging series.

**Comment by terrelsa13** [comment]
I do not. If you want to send a working test API call my way I'd greatly appreciate it

**Comment by SenorSmartyPants** [comment]
`http://server:8096/Users/<userID>/Items/?IncludeItemTypes=Series,Season&ParentID=<LibraryID>&Recursive=true&SortBy=SortName&tags=<tagname>`
That would return all tagged Series and seasons. You'd have to walk thru all the IDs to get the child episodes for each tagged series/season

`http://<server>:8096/Users/<userID>/Items/?Filters=isPlayed&IncludeItemTypes=Episode&ParentID=<season or seriesID>&Recursive=true&SortBy=SortName`
Get's played episodes for that season/series.

**Comment by terrelsa13** [comment]
I remember another reason why I went with paths instead of IDs for the libraries. For some reason on my Emby and JF none of the following API calls used during the setup step
`http://watch.tv/jf/Library/VirtualFolders?api_key=abcdef8abc2a1243b2f71235abc33123`

`http://watch.tv/jf/Library/MediaFolders?api_key=abcdef8abc2a1243b2f71235abc33123`

`http://watch.tv/jf/Items/f8bb51b41feb98f012d0a699dc744201/Ancestors?api_key=abcdef8abc2a1243b2f71235abc33123`
give a matching Id when a specific media items library Id.

For example a movie's parent ID should be the movie libraryId given from the above API calls.
`http://watch.tv/jf/Users/fcc078ae1d8047458d2e3ca459e88d09/Items?includeItemTypes=Movie&IsPlayed=True&Fields=ParentId&Recursive=true&api_key=abcdef8abc2a1243b2f71235abc33123`

`http://watch.tv/jf/Users/fcc078ae1d8047458d2e3ca459e88d09/Items/f8bb51b41feb98f012d0a699dc744201?api_key=abcdef8abc2a1243b2f71235abc33123`

But for me the two Movie LibraryIds do not match. Do you get matching IDs on your setup?
Am I missing something?

(For episodes I expect the ParentId of the Series to be the TV LibraryId. This is also not matching.)

**Comment by terrelsa13** [comment]
Wrong place. Moving to [the correct issue](https://github.com/terrelsa13/media_cleaner/issues/13#issuecomment-1084745784).

**Comment by terrelsa13** [comment]
@SenorSmartyPants 
I did not forget about this. I have been working on it when I can. I have it implemented for movies, movie libraries, episodes, seasons, series, and tvshow libraries. Only videos, trailers, audio, and audio books left. These should be easier to implement after getting movies and tvshows working. Do you mind testing it out once I finish implementing it for the other media types? I am estimating I'll have something to test out in about 1-2 weeks.

**Comment by SenorSmartyPants** [comment]
I can test it against my library. I would only be running against TV stuff at the moment. Maybe Movies.

**Comment by terrelsa13** [comment]
@SenorSmartyPants

Ok, try out [this branch](https://github.com/terrelsa13/media_cleaner/tree/media_cleaner_2p0_beta) whenever you get a chance.

Breaking Changes In This Branch:
---Old Configuration will not work; need to build new config---

*Created a default config template (media_cleaner_config_default.py)
*Default values in media_cleaner_config_default.py can be modified before the initial setup; it will then load your customized default values
*When assigning libraries to a user; user input now able to accept multiple libraries (comma separated)
*Only show libraries user has permission to access
*Add [blacktag feature](https://github.com/terrelsa13/media_cleaner/issues/16) for episodes, seasons, series, and movies (audio and audio books WIP)
*Add [whitetag feature](https://github.com/terrelsa13/media_cleaner/issues/16) for episodes, seasons, series, and movies (audio and audio books WIP)
*Multiple blacktags and whitetags allowed (comma separated)
*Remove Trailers as a media option
*Remove generic Video as a media option
*Breakup keep_favorites_advanced_xzy binary string into individual config options
*Add additional keep favorite option (some vary depending on emby vs jellyfin i.e. favorting tv show networks)
*All filtering now done using IDs instead of path names
*Fix issue where user1 has a media item favortied and unwatched; user2 watches the media item; media item was deleted
*Remove request_not_played option
*Lower API request attempts from 6 to 4. Essentially shortening the time needed to wait for a connection error from 63s to 15s
*Setup still allows choosing whitelist or blacklist when selecting media libraries; the selected libraries will be populated in the chosen user_bl_libs or user_wl_libs config variable. The not chosen libraries will populate the other user_bl_libs or user_wl_libs config variable
*user_bl_libs and user_wl_libs now store userId, libraryId, collectiontype, networkpath, and path.
*No longer storing admin_username in config

**Comment by SenorSmartyPants** [comment]
Sorry I haven't tested this yet. Life has been getting in the way. I will get back around to looking at this.

**Comment by terrelsa13** [comment]
Np. I have been trying to test this every which way I can. I am sure I have missed something. But the bulk of it should be there.
