### ISSUE TITLE
Jellyfin 10.8 Beta2

### ISSUE THREAD

**Issue by AussieAbroad** [terrelsa13/media_cleaner#17]
Hi team, just checking to see if this is working with abovementioned. I tried to configure again and it is sending an authorisation error. Thank you

**Comment by terrelsa13** [comment]
@AussieAbroad 
Thanks for the heads up! I do not usually track to Beta releases. BUT I just happen to be making substantial changes to the way the script queries and processes media items. Once I get those changes smoothed out; I can load JF 10.8 Beta2 and see what needs to be updated.

**Comment by terrelsa13** [comment]
@AussieAbroad 
Just updated to JF 10.8.0 Beta2, deleted my config, ran thru setup, and performed a dry-run. 

Please verify the correct admin username and admin password were used during setup.
If that is not the issue a new API authorization key may be needed.

Either delete the config and re-run the script.
Or
A new API authorization key can be created in the GUI (Dashboard > Advanced > API Keys. Then copy paste this key into the config file to replace the old one used with `access_token`.

**Comment by AussieAbroad** [comment]
Thank you for the quick reply. I copy and pasted the API as suggested and all seems to be working OK now. Not sure what happened but much appreciated

**Comment by AussieAbroad** [comment]
Hi and thank you for your past responses

I  have been having troubles getting the script to run on 10.8 beta 2. It
goes through the scanning process VERY slowly and then does not delete at
the end. Gets several error messages. I am using Python 3.9 as you will
note. See attached photo shots for error messages

Please let me know if you need any further information. I have been using
your script for a while so know the configuration setup and it worked fine
with 10.7 (maybe a reason I should not have upgraded yet)

Cheers and thank you

**Comment by terrelsa13** [comment]
@AussieAbroad 
Please upload all of the output to [pastebin.com](https://pastebin.com/) and reply with the link.
Then in a different [pastebin.com](https://pastebin.com/) link upload your configuration and reply with that link as well.

**Comment by terrelsa13** [comment]
@AussieAbroad I was able to run v1.2.3 of the media_cleaner script using python v3.10.4 without any issues.

When you get a chance, please upload the output you are seeing along with your config into pastebin so I can help figure out how to get the script working for you.

**Comment by terrelsa13** [comment]
@AussieAbroad 
I think I see what you are talking about. This is a limitation of the way v1.x.x of the script is written.

```
#----------------------------------------------------------#
#  0 - Request metadata only for played media items in monitored libraries
#   When single user, script will complete faster, no downside
#   When multiple users, script will complete faster BUT...
#   The script will only be able to keep a media item when a user has set it as a favorite and has played it
#  1 - Request metadata for played and not played media items in monitored libraries
#   When single user, script will complete slower, slower is the downside
#   When multiple users, script will complete slower BUT...
#   The script is able to keep a media item when a user has set it as a favortie but has not played it
# (1 : default)
#----------------------------------------------------------#
request_not_played=1
```
This bandaid was added back in January going from [v1.0.2 --> v1.2.0](https://github.com/terrelsa13/media_cleaner/commit/bf1fc4cc10f60e6b435295de1e15eb52e9abc864) to work around an issue with having multiple users and favorited media items.

## Temporary Work Around:
Add/change ```request_not_played=0``` to the config. The script will run "faster" because it does not need to request played and unplayed media items to determine if something is watched by user1, unwatched by user2, and set as a favorite by user2. But as shown in the configuration snippet above, there is a downside when monitoring multiple users.

## Long Term Fix:
[The Beta branch](https://github.com/terrelsa13/media_cleaner/tree/media_cleaner_2p0_beta) of this script (aka v2.x.x) has several changes, one of which addresses this issue; completely removing the ```request_not_played=``` option from the config. The recommendation moving forward will be to use v2.x.x of the script.

The plan for now is to merge the v2.x.x branch into main sometime in early June. Once this happens v1.x.x of the script will become obsolete. The v2.x.x script is not backwards compatible with the existing v1.x.x config. It is recommend to either make a backup copy of the existing v1.x.x script and config or run v2.x.x in a completely separate folder.

Jellyfin 10.8.0-beta3, Python >=3.8, and v2.x.x. of the script run as expected.

During setup v2.x.x will have a few new prompts which can be read in detail on [the Beta branch](https://github.com/terrelsa13/media_cleaner/tree/media_cleaner_2p0_beta).

**Comment by AussieAbroad** [comment]
Hi @terrelsa13

I see my past pastebin files could not be loaded as I had to create them in PRIVATE mode. See below updated Pastebin and ControlC links showing the issues

Configuration file - https://pastebin.com/wjYvfc6m

Output file from above configuration showing Delete Errors - identifies file but does not delete at end -   https://controlc.com/a104818e

Output file error when trying to setup Beta2 version - does not setup -  https://controlc.com/4c68fa24

This will now give a clear picture of the errors

**Comment by terrelsa13** [comment]
This looks like a permissions issue.

> Output file from above configuration showing Delete Errors - identifies file but does not delete at end - https://controlc.com/a104818e

`urllib.error.HTTPError: HTTP Error 500: Internal Server Error`

The server is receiving the request to delete the file and responding back it is not able to or refuses to actually perform the delete.

#

This also looks like a permissions issue.

> Output file error when trying to setup Beta2 version - does not setup - https://controlc.com/4c68fa24

`urllib.error.HTTPError: HTTP Error 401: Unauthorized`
`RuntimeError:`
`AUTH_ERROR: User Not Authorized To Access Library`

The `SMPCE` user is either not an Admin. Or the password for `SMCPE` was typed incorrectly and the script is unable to fetch the `auth_key`.

#

Copy/Paste this into a browser on your server:
`http://localhost/emby/Users/Me?api_key=2a02171ecc5a478cb9fcc37624acc349`

Copy the returned data into pastebin. In pastebin enable "Syntax Highlighting" and select "JSON" as the "Syntax Highlighting". Then reply with the pastebin link.

If no data is returned; `2a02171ecc5a478cb9fcc37624acc349` is not a valid API/Authentication Key.

**Comment by AussieAbroad** [comment]
Thank you. When I saw the authorisation error you outlined I did 2 things. I updated the SMPCE password and saved it. I also when into the SMPCE profile and unchecked ALLOW MEDIA DELETION FROM ALL LIBRARIES. I then saved that, then when back in and checked ALLOW MEDIA DELETION, then saved it again. I then ran the setup again for the Media Cleaner to create a new configuration file (on old version, not Beta version). This worked and then ran it in test mode, then active mode. It is now deleting again in line with the configuration. I would appear the password reset on the Admin User updated the Jellyfin database to allow this to be correctly recognised. Thank you, I will update if any further challenges (now working so this issue can be closed)
