### ISSUE TITLE
Delete unwatched media 

### ISSUE THREAD

**Issue by septarchy** [terrelsa13/media_cleaner#25]
Hello sir,

I rather delete stuff I haven't watched for months. This means it's not worth saving... 

Can you also make it so that things not watched will be deleted after x couple of months...?

Best regards!

**Comment by terrelsa13** [comment]
@septarchy 
I want to make sure I understand your request. Is the example I am showing below what you want the script to do?

### Example

- Your library has x4 media items
   * Created >= 60 days ago
      * Media Item#1 - Watched
      * Media Item#2 - Unwatched
   * Created < 60 days ago
      * Media Item#3 - Watched
      * Media Item#4 - Unwatched

When the script is run you want to:
- Delete
   * Media Item#1 - Because it was created >=60 days ago
   * Media Item#2 - Because it was created >=60 days ago
- Keep
   * Media Item#3 - Because it was created <60 days ago
   * Media Item#4  - Because it was created <60 days ago

**Comment by septarchy** [comment]
Yes indeed, this keeps your media library a bit cleaner. It doesn't delete favorites I guess...?

Also if watched >1x = keep media would be really great addition :)

**Comment by terrelsa13** [comment]
This is already a feature. But I see I broke it just a little bit during the version2.0 rewrite; my bad. Luckily it appears to be an easy fix.

Check out the `max_age_*` config options. This will do what you are looking for once I push the fix.

Be very careful with the `max_age_*` config options. Setting the value too low (i.e. 5 days) will delete all media of that type with a creation date >=5 day ago.
```
#----------------------------------------------------------#
# CAUTION!!!   CAUTION!!!   CAUTION!!!   CAUTION!!!   CAUTION!!!
# Do NOT enable any max_age_xyz options unless you know what you are doing
# Use at your own risk; You alone are responsible for your actions
# Enabling any of these options with a low value WILL DELETE THE ENTIRE LIBRARY
# Delete media type if its creation date is x days ago; played state is ignored; value must be greater than or equal to the corresponding played_age_xyz
#   0-730500 - number of days to wait before deleting "old" media
#  -1 - to disable managing max age of specified media type
# (-1 : default)
#----------------------------------------------------------#
max_age_movie=-1
max_age_episode=-1
max_age_audio=-1
max_age_audiobook=-1
```
The `max_keep_favorites_*` config options are obsolete. I meant to remove them from the config builder but it appears I did not. Instead use any of the other `keep_favorites_*` config options to have favorited media items kept. You can also whitetag media items to keep them too.

I will look into how easy/hard it will be to check for the number of times a media item is played as a criteria for deleting it or keeping it.

**Comment by terrelsa13** [comment]
Try out [this branch](https://github.com/terrelsa13/media_cleaner/tree/max_age_--bug-fix-and-play-count) with the max_age_* bug fix and the feature request to keep media based on number of times watched. Let me know if you run into any issues.


1. You will need to create a new configuration file so the new options are available.
2. You can force this by opening your configuration file, deleting the `DEBUG=False` line, and saving.
3. Then run the script.
4. Open the new configuration file once it is created.
5. Change `played_age_movie=60`. This a "safety" and must be >= `max_age_movie=60` in step#9.
6. Change `keep_favorites_movie=1` or `keep_favorites_movie=2`. This will keep favorited media items.
7. Change `played_count_movie_action=2`. This will keep media items played >= the value used in step#8.
8. Change `played_count_movie=2`. This is the number of play counts.
9. Change `max_age_movie=60. This is the least number of days ago a media item must have been created in order to be considered for deletion.
10. Run the script again. Make sure the output make sense.
11. Once the script is running as intended; set it up in crontab or another job scheduler to run automatically.


I still have some work to do to figure out how to implement the feature request to keep media based on number of times watched. Currently it is only considering individual monitored users and does not consider multiple users who have played a media item different amounts of times. I will work on making it multi-user friendly sometime in the future. For now this will sit in the branch until I find the time to complete the feature.

**Comment by terrelsa13** [comment]
@septarchy 
Wanted to say thanks for your request to delete based on the number of play counts for a media item. It helped me see a way to make a major improvement in setting up the script and helped simplify the configuration process during setup buy using "Filter Statements".

I am deleting the branch I referenced above and pointing you to [this branch](https://github.com/terrelsa13/media_cleaner/tree/v3.0.x_BETA). This will eventually make it into the master. But for now it will live in a branch.

**Comment by septarchy** [comment]
Great to hear :) thanks for making this piece of code! 👍
