### ISSUE TITLE
Error when configuring max_age_movie=

### ISSUE THREAD

**Issue by keppo070** [terrelsa13/media_cleaner#31]
```Traceback (most recent call last):
  File "/home/xxx/dir/python/mumc/media_cleaner.py", line 6487, in <module>
    deleteItems=get_media_items()
  File "/home/xxx/dir/python/mumc/media_cleaner.py", line 3703, in get_media_items
    itemIsPlayed=get_playedStatus(cfg.played_age_movie,item['UserData']['PlayCount'],cut_off_date_movie,item['UserData']['LastPlayedDate'],cfg.max_age_movie,max_cut_off_date_m
KeyError: 'LastPlayedDate'
```

Script Verion: 2.1.7
blacklist mode

anything **but** ```max_age_movie=-1``` will generate this error

**Comment by terrelsa13** [comment]
```
KeyError: 'LastPlayedDate'
```
This error is saying the media item being inspected does not have the `['UserData']['LastPlayedDate']` field.

v2.1.7: Line# 3701 - 3705
```
#Decide if media item is played and meets the cutoff date criteria or max cutoff date criteria
if ((('PlayCount' in item['UserData']) and ('LastPlayedDate' in item['UserData'])) or (cfg.max_age_movie >= 0)):
    itemIsPlayed=get_playedStatus(cfg.played_age_movie,item['UserData']['PlayCount'],cut_off_date_movie,item['UserData']['LastPlayedDate'],cfg.max_age_movie,max_cut_off_date_movie)
else:
    itemIsPlayed=False
```
You can see above the script checks if `LastPlayedDate` exists first with this `('LastPlayedDate' in item['UserData'])`. Only when `LastPlayedDate` exists should line# 3703 execute. This should technically not be able to happen. Please turn on `DEBUG`, run the script again, it should fail here again, and send me everything from the output.

**Comment by keppo070** [comment]
config and resulting debug

[debug_v2.txt](https://github.com/terrelsa13/MUMC/files/9228558/debug_v2.txt)
[media_cleaner_config.py.txt](https://github.com/terrelsa13/MUMC/files/9228561/media_cleaner_config.py.txt)

**Comment by terrelsa13** [comment]
All outputs from v1, v2, and v3 appear to have completed without throwing the `KeyError: 'LastPlayedDate'`. I am a little confused; was there a change made to your server or config to make it work?

**Comment by keppo070** [comment]
I mad e two issues. This one is related to max_age_movie not working in v2 as shown in de debug_v2.txt. If you change de media_vleaner_config.py and set the max_age_movie to -1 it is working. (Except I dont get any tvshows in my listing) #32 

if i understand correctly there is no option in v3 to do both. delete after 14d is played => 1 && created => 365

**Comment by terrelsa13** [comment]
I was able to recreate the `KeyError: 'LastPlayedDate'` issue originally mentioned in v2.

When max_age_* is >=0 the check was or'd which was allowing media items without the `item['UserData']['LastPlayedDate']` field to call `get_playedStatus()`.

I have uploaded the fix for this as v2.1.8.

>if i understand correctly there is no option in v3 to do both. delete after 14d is played => 1 && created => 365

If I recall v1 should have not been able to do both. When `max_age_*` was >=0 then 'max_played_*` was ignored.

For v2.1.7 and earlier it appears the bug that was just fixed did not allow anyone to properly use the `max_age_*` functionality. With fix in v2.1.8 it should now be working, let me know if you run into any more issues with it.

Hmm... for v3 you are correct. I seem to have missed allowing media to be deleted based off played age and created age. Looks like v3 will remain in BETA until I figure out a clean way to incorporate played and created filtering.

**Comment by terrelsa13** [comment]
v3.1.1-beta has been updated to allow filtering for both played and created media items. You will have to let it rebuild your configuration to see the new options. You will then be able to create Filter Statements that will allow deleting media played after a certain amount of days AND delete media created after a certain amount of days.

**Comment by keppo070** [comment]
> If I recall v1 should have not been able to do both. When `max_age_*` was >=0 then 'max_played_*` was ignored.

I noticed this also. That's why i switched to 2.1.7 and because it was out of support I switched to v3
