### ISSUE TITLE
Consider a "simple mode" during initial configuration?

### ISSUE THREAD

**Issue by zilexa** [terrelsa13/media_cleaner#71]
Jesus, you have managed to create an extremely extensive but also very complex solution for something that was originally meant to simply delete eps and movies after watched X days ago. My compliments, but also, now I have an issue and no clue why. 

The old version stopped working so I switched to yours (v2.1.1) but that version never seems to consider Movies, even though the library details are in the config file. 

So now switching to your latest version, there is A LOT of config options to walk through and some are quite confusing, especially if you have no idea of all the added options like max age etc. 

Just a suggestion to a add a "simple mode" that just covers deleting eps/movies/books after X days watched/read with exclusion of items marked as favourite.

**Comment by terrelsa13** [comment]
> Jesus, you have managed to create an extremely extensive but also very complex solution for something that was originally meant to simply delete eps and movies after watched X days ago. My compliments, but also, now I have an issue and no clue why.

Everyone wants to manage their media differently. I made the config options as simple and straight forward as possible.

> So now switching to your latest version, there is A LOT of config options to walk through and some are quite confusing, especially if you have no idea of all the added options like max age etc.

The old ```max_age_*``` config option is equivalent to the ```created_filter_*``` config option.
It looks more complicated; but it is meant to simplify the myriad of different ways people want to manage deleting their media.

- **Filter Statements** tell MUMC how to find media items.
  - Filter Statements have the word ```filter``` in their name
- **Behavioral Statements** tell MUMC how to decide which items found with the Filter Statement should be deleted.
  - Behavioral Statements have the word ```behavior``` in their name

Please read through the [README](https://github.com/terrelsa13/MUMC/tree/MUMC_v4-BETA#cool-how-do-i-use-this) for MUMC v4. If you still have specific questions after reading it all the way through; I will do my best to answer them.

> Just a suggestion to a add a "simple mode" that just covers deleting eps/movies/books after X days watched/read with exclusion of items marked as favourite.

The default configuration should already be setup to do this.
All that needs to be done is setting the number of days.

**Comment by zilexa** [comment]
I was referring to a much, much simpler version without all those features. But I do appreciate you are going for a catch all solution.
@terrelsa13 To limit scrolling through a long config.py for users that simply want watched media to be deleted automatically without blacklist/whitelist/tags etc, may I at least suggest to move "REMOVE_FILES=False", "UPDATE_CONFIG=False" and the DEBUG option to the top?

This might seem completely useless and meaningless to you, but there are plenty of people who are not technical, don't work with script normally and will be put off simply scrolling through a long config file. It is really a lowhanging fruit sort of.
Also, this way you would be moving all the elements that every user need to the top, and elements not every user necessarily needs below that.

**Comment by terrelsa13** [comment]
I was conflicted on doing what you are suggesting for the v4 update. Ultimately decided to keep those config options away from the top. Here is why...

- Decided not to put ```REMOVE_FILES``` near the top because of the non-technical users we are talking about. I do not want anyone getting too excited and setting it to ```True``` just because it was easy to find at the top. Most likely this would lead to a bunch of their media media being deleted. I would rather they have to go looking for this config option when they need it. I can help someone who cannot figure out how to delete their media files. I cannot help someone who has accidentally deleted their media files.

- ```UPDATE_CONFIG``` and ```DEBUG``` Same train of thought. The non-technical users are not going to want to see these at the top; and not very likely not use them.

##

After the config is created the options do not need to be in a specific order. They can be moved around. The comments above each config option can even be deleted. But ALL of the config options do need to be there.

If a user is only interested in a few of the config options; those can be manually moved to the top of the config and everything else moved to the bottom. However if the config is updated or re-created it will be put it back in the original order.

The best I can offer is a future feature to preserve the config order when ```UPDATE_CONFIG``` is used.

**Comment by terrelsa13** [comment]
@zilexa Finally got around to simplifying the generated `mumc_config.yaml`.

To satisfy my non-tech users I have simplified the default config MUMC generates.
To satisfy my tech users all of the additional config variables are available on the [wiki](https://github.com/terrelsa13/MUMC/wiki).
* [Configuration File Examples](https://github.com/terrelsa13/MUMC/wiki/Configuration_File_Examples)
   * [Minimum Configuration File Example](https://github.com/terrelsa13/MUMC/wiki/Configuration_File_Examples-Minimum_Configuration_File_Example)
   * [Full Configuration File Example](https://github.com/terrelsa13/MUMC/wiki/Configuration_File_Examples-Full_Configuration_File_Example)
* [Configuration Tree](https://github.com/terrelsa13/MUMC/wiki/Configuration_Tree)

Starting at MUMC [v5.8.2-beta](https://github.com/terrelsa13/MUMC/releases/tag/v5.8.2-beta) the config no longer needs to have EVERY config variable. Only the minimum described above. Any additional config variables can be added individually. Anything not in the config, will use default values.

Sometime in the near future these updates will be merged into the trunk (MUMC-Latest). For now they are on the MUMC_dev branch.

**Comment by terrelsa13** [comment]
The changes mentioned above are now in the trunk as [v5.8.29](https://github.com/terrelsa13/MUMC/releases/).
