### ISSUE TITLE
Bug: TypeError: 'HTTPError' object is not subscriptable

### ISSUE THREAD

**Issue by Mavyre** [terrelsa13/media_cleaner#81]
When I try to first execute MUMC, and when asked for login credentials, I get the following error:
```
An error occured, a maximum of 3 attempts met, and no data retrieved from the "get_authentication_key" lookup.
Traceback (most recent call last):
  File "/home/MUMC/./mumc.py", line 8380, in <module>
    import mumc_config as cfg
ModuleNotFoundError: No module named 'mumc_config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/MUMC/./mumc.py", line 8459, in <module>
    build_configuration_file(None,update_config)
  File "/home/MUMC/./mumc.py", line 1518, in build_configuration_file
    auth_key=get_authentication_key(server_url, username, password)
  File "/home/MUMC/./mumc.py", line 846, in get_authentication_key
    return(data['AccessToken'])
TypeError: 'HTTPError' object is not subscriptable
```

Tried multiple debugging settings, but I can't get more errors nor the HTTPError returned by Jellyfin...

**Comment by terrelsa13** [comment]
Sorry for the delay here. Is this still an issue?

**Comment by Mavyre** [comment]
Didn't retry, however couldn't make it work a few times when I tested. I tried every possibilities of accounts, URLs, with or without HTTPS, with or without a reverse proxy. Directly from the container, and outside the container. Still the same strange error

**Comment by terrelsa13** [comment]
The script is not able to retrieve the authentication key. This is likely because the user chosen during setup did not have the proper settings in Jelly Dashboard.

Please follow the steps laid out [here](https://github.com/terrelsa13/MUMC/issues/42#issuecomment-1279961448) to verify the user you are selecting has the proper settings. If you do not have an official "admin" user account I suggest you create one. That way the "normal" users don't need to have admin access.

**Comment by terrelsa13** [comment]
No response. Closing.
